import type { Metadata } from 'next';
import './globals.css';
import { Footer, Navbar } from '@/components';
import { poppins } from '@/config';
import { Providers } from '@/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.className}>
        <div className="min-h-screen bg-gradient-to-b from-zinc-900 to-zinc-800 text-white overflow-hidden">
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  );
}
