import type { Metadata } from 'next';
import '../globals.css';
import { Footer, Navbar } from '@/components';
import { poppins } from '@/config';
import { Providers } from '@/providers';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={poppins.className}>
        <NextIntlClientProvider messages={messages}>
          <div className="min-h-screen bg-gradient-to-b from-white to-gray-200 dark:from-zinc-900 dark:to-zinc-800 overflow-hiddenn ease-in-out duration-200 transition-all">
            <Providers>
              <Navbar />
              {children}
              <Footer />
            </Providers>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
